### ISSUE TITLE
ERROR: Permission to AutoTux/SysTux.git denied to paradigm-lab

### ISSUE THREAD

**Issue by paradigm-lab** [AutoTux/SysTux#3]
I have got a PR but can't push to the repository. Because I am not add as a collaborator in the repository.

**Comment by JuanBindez** [comment]
See if you can send PR now

**Comment by paradigm-lab** [comment]
Still getting the same error

**Comment by paradigm-lab** [comment]
``` bash
ERROR: Permission to AutoTux/SysTux.git denied to paradigm-lab.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by JuanBindez** [comment]
> ```shell
> ERROR: Permission to AutoTux/SysTux.git denied to paradigm-lab.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> ```

There seems to be a problem with the name of the repository, try making a new fork or clone and try making a new PR
